os: osx
osx_image: xcode11.3
language: objective-c
script:
- "./scripts/install-signing"
- "./scripts/version"
- "./scripts/build"
branches:
  only:
  - "/^\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: releases
  api_key:
    secure: OHbKz9sAT5iTV1UshO6W5t24BL2dQwYQ90yVL2QOp4vMDAw9WIKZxBfvnYL33NHxFCiXGbkdmC6jiFjxhWCirL1bg830jqjERk3l6Kxw4Nqkb6aYr5udcuatFwAwYfxlN+Kxfi9F5KoHDUkjvL56oW3liofEq3JT/yz7Tl6zRFduSsauQ9dNHdax3Zfc2arnV2SM3sDpMUVoNz7C781gJlyoUGhJQf7yaG3Qj6CaZtNm94rnJRQEJOQRvXc+t3WadrQ4+DvHnww1dqRMjUybxHpwyRkw/C8CZM4Zuan6dakMs2OMUht99QzvMhqWudSVg05IS2iFf91dZWcbdDOPLkcny7aL0TqdrAJKb1f1runa0+AuFJBri7teyxcJAEYmF8OSKd2038T8jB7wOaghbwTHquBvo17sUlmkNXgSpHic4fuSTF5//riUoLA1fwJqxsD+QkaUXDK48E1ZzpV4HEfzIz9Q2WZwLBMl0QdtjR9TQcEz6CAGOcplbp+G3K0JvD0OtS5sGPN132DmqYkBNmhfZOW6rfN9UE0ZWOiTLF3k4GeqwUerGolM3tM2rfwtFPaErfo7UGqlXv0IIpH9dGHCIJE34UxfKkfhrAfuVR9CcRR6K+RTUlut0CHiM6hAHzeicRJ78bH6KCMYFQWU6XcYakYyclctT/yytIaYVag=
  skip_cleanup: true
  file: artifacts.tar.gz
  on:
    repo: mrketchup/cooldown
    tags: true
