osx_image: xcode9
language: objective-c
script:
- "./scripts/install-signing"
- "./scripts/version"
- "./scripts/build"
branches:
  only:
  - develop
  - "/^\\d+.\\d+.\\d+$/"
deploy:
  provider: releases
  api_key:
    secure: JEzJkG+hAVS3wFXVLWS45lg7/jQk23wENJ9Fcqh/8iZVxdpykT4DsYCOpw/OHhw3xemZmUSa3fFOHl+THM3wi3N4ijJvTmcwrxE4sGy3NYBV8iCYLT3Ngb/635t+YFmT6kew+eOi2xTmWXSZe500ZYm/4py2DsV90kY0FB+Q0LDHg47bR3LPR1mxyKT9z4/h/PQylLWDhMe/cE3aUYtJ8LQ4Mf2rzGgC37Ndd/s1KggA4xSC2jbkFyywbrabn3fwncQDibQgoG1q31vjbO8CRGIRC/CUBXaROOGpW8ERyxiWx4+DdFCY9zZMGw59/LLfMXBxVU7kbh8evdJ7MGhS9m+uxj/iB3hn6rQ8sWzJDiGVWHCstPCPB+4WLPRhLAn7Qg4h6tvIh8Wrh6F+GeHHL3q9DXZyh5+0zbn7GhXYYVs2mBv7xbVDvmjrb5htIH/LzxyONhdIChrWHYk0i+G/gsrUvC48kxxDoAmRAFimGtmErPXOEHjBSfOsBbBc2mMM6OuOwbizXec0LI4oAXYVQO/LNXMQrM+CYJxOMyIzl2kuyL5VdlQHV5WN4jAJfubKlMQrCP9NH8cMHIFtQkfU5WJrzwLpxQ3shaCTBA9zmI0puIHEhIkm9JR+EVNAkh/krjod5AlgI86At2wFC2JfacY6QINrAPawUh+eUa1xpMQ=
  file: artifacts.tar.gz
  skip_cleanup: true
  on:
    tags: true
