#!/bin/bash
set -e

echo -e "\n\033[0;34m*** BUILD ***\n\033[0m"

set -o pipefail && \
xcodebuild archive \
  -project Cooldown.xcodeproj \
  -scheme Cooldown \
  -configuration Release \
  -archivePath artifacts/Cooldown.xcarchive | xcpretty --color

echo -e "\n\033[0;34m*** COMPRESSING ARTIFACTS ***\n\033[0m"
tar -zcvf artifacts.tar.gz artifacts/
