#!/bin/bash
set -ev

echo -e "\n\033[0;34m*** BUILD ***\n\033[0m"
set -o pipefail && \
xcodebuild archive \
  -project Cooldown.xcodeproj \
  -scheme Cooldown \
  -configuration Release \
  -archivePath artifacts/cooldown.xcarchive | xcpretty --color

echo -e "\n\033[0;34m*** EXPORT ***\n\033[0m"
set -o pipefail && \
xcodebuild \
  -exportArchive \
  -exportOptionsPlist signing/appstore.plist \
  -archivePath "artifacts/cooldown.xcarchive" \
  -exportPath "artifacts" | xcpretty --color

echo -e "\n\033[0;34m*** COMPRESSING ARTIFACTS ***\n\033[0m"
tar -zcvf artifacts.tar.gz artifacts/